export const cardValues = {
    1: {
        name: "wowlo1",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 1,
    },
    2: {
        name: "wowlo2",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 2,
    },
    3: {
        name: "wowlo3",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 3,
    },
    4: {
        name: "wowlo4",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 4,
    },
    5: {
        name: "wowlo5",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 5,
    },
    6: {
        name: "wowlo6",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 6,
    },
    7: {
        name: "wowlo7",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 7,
    },
    8: {
        name: "wowlo8",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 8,
    },
    9: {
        name: "wowlo9",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 9,
    },
    10: {
        name: "wowlo10",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: '../imgs/cardimg.jpg',
        id: 10,
    },

}
