export const cardValues = {
    pierwsza: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 1,
    },
    druga: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 2,
    },
    trzecia: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 3,
    },
    cztery: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 4,
    },
    piec: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 5,
    },
    szesc: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 6,
    },
    siem: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 7,
    },
    osiem: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 8,
    },
    dziew: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 9,
    },
    dies: {
        name: "wowlo",
        value: "dkasdfas",
        link1: "",
        link2: "",
        picture: "",
        id: 10,
    },

}
